In [350]:
from urllib.request import urlopen
import json
from pandas import json_normalize
import pandas as pd

Register of inhabitants. Population of the city of Barcelona by sex and academic level

In [351]:
url1 = 'https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=ac73b03b-247c-4c05-b773-72b3ca25dc74&limit=876'
fileobj1 = json.load(urlopen(url1))
#print(fileobj1)

In [352]:
fileobj1.keys()

dict_keys(['help', 'success', 'result'])

In [353]:
fileobj1['result'].keys()

dict_keys(['resource_id', 'fields', 'records', '_links', 'limit', 'total'])

In [354]:
sub_df1 = pd.json_normalize(fileobj1['result']['records'])

In [355]:
sub_df1

,Codi_Districte,Sexe,Nom_Districte,Nom_Barri,Nombre,Codi_Barri,Nivell_academic,_id,Any
0,1,Dona,Ciutat Vella,el Raval,440,1,Sense estudis,1,2020
1,1,Dona,Ciutat Vella,el Barri Gòtic,146,2,Sense estudis,2,2020
2,1,Dona,Ciutat Vella,la Barceloneta,273,3,Sense estudis,3,2020
3,1,Dona,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",223,4,Sense estudis,4,2020
4,2,Dona,Eixample,el Fort Pienc,262,5,Sense estudis,5,2020
...,...,...,...,...,...,...,...,...,...
871,10,Home,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,124,69,No consta,872,2020
872,10,Home,Sant Martí,el Besòs i el Maresme,233,70,No consta,873,2020
873,10,Home,Sant Martí,Provençals del Poblenou,174,71,No consta,874,2020
874,10,Home,Sant Martí,Sant Martí de Provençals,239,72,No consta,875,2020
875,10,Home,Sant Martí,la Verneda i la Pau,279,73,No consta,876,2020

In [356]:
sub_df1['Nivell_academic'].value_counts()

Batxillerat elemental / graduat escolar / ESO / FPI          146
Sense estudis                                                146
Batxillerat superior / BUP / COU / FPII / CFGM grau mitjà    146
No consta                                                    146
Estudis universitaris / CFGS grau superior                   146
Estudis primaris / certificat d'escolaritat / EGB            146
Name: Nivell_academic, dtype: int64

Elementary school / school graduate / ESO / FPI 

Without studies 

High school / BUP / COU / FPII / CFGM Intermediate Grade

No records 

University studies / CFGS higher degree

Primary education / certificate of schooling / EGB

In [357]:
sub_df1 = sub_df1.rename(columns = {"Nom_Districte": "District", 
                                    "Codi_Districte" : "District_Code", 
                                    "Nom_Barri": "Neighborhood",
                                    "Codi_Barri": "Neighborhood_Code",
                                    "Sexe": "Sex",
                                    "Nivell_academic": "Academic_Qualification",
                                    "Nombre":"Population"})

In [358]:
educational_stages = {"Batxillerat elemental / graduat escolar / ESO / FPI": "Elementary school / school graduate / ESO / FPI",
       "Sense estudis": "Without studies",
       "No consta": "No records",
       "Batxillerat superior / BUP / COU / FPII / CFGM grau mitjà": "High school / BUP / COU / FPII / CFGM Intermediate Grade",
       "Estudis primaris / certificat d'escolaritat / EGB": "Primary education / certificate of schooling / EGB",
       "Estudis universitaris / CFGS grau superior": "University studies / CFGS higher degree"}

In [359]:
sub_df1["Academic_Qualification"] = sub_df1["Academic_Qualification"].map(educational_stages)

In [360]:
sex = {"Dona": "Women",
       "Home": "Men"}

In [361]:
sub_df1["Sex"] = sub_df1["Sex"].map(sex)

In [362]:
table1 = sub_df1.drop(columns=["_id", "Any"])

In [363]:
table1

,District_Code,Sex,District,Neighborhood,Population,Neighborhood_Code,Academic_Qualification
0,1,Women,Ciutat Vella,el Raval,440,1,Without studies
1,1,Women,Ciutat Vella,el Barri Gòtic,146,2,Without studies
2,1,Women,Ciutat Vella,la Barceloneta,273,3,Without studies
3,1,Women,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",223,4,Without studies
4,2,Women,Eixample,el Fort Pienc,262,5,Without studies
...,...,...,...,...,...,...,...
871,10,Men,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,124,69,No records
872,10,Men,Sant Martí,el Besòs i el Maresme,233,70,No records
873,10,Men,Sant Martí,Provençals del Poblenou,174,71,No records
874,10,Men,Sant Martí,Sant Martí de Provençals,239,72,No records
875,10,Men,Sant Martí,la Verneda i la Pau,279,73,No records

In [364]:
#table1.groupby(['District', 'District_Code', 'Neighborhood', 'Neighborhood_Code', 'Sex', 'Academic_Qualification', 'Population']).sum()

Population of the city of Barcelona according to sex, five-year age and nationality

In [365]:
url2 = 'https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=eaf3860e-a771-4dd2-827e-2aa919254329&limit=6132'
fileobj2 = json.load(urlopen(url2))
#print(fileobj3)

In [366]:
fileobj2.keys()

dict_keys(['help', 'success', 'result'])

In [367]:
fileobj2['result'].keys()

dict_keys(['resource_id', 'fields', 'records', '_links', 'limit', 'total'])

In [368]:
sub_df2 = pd.json_normalize(fileobj2['result']['records'])

In [369]:
sub_df2

,Codi_Districte,Sexe,Nom_Districte,Nom_Barri,Codi_Barri,Nombre,_id,Edat_quinquennal,Any,Nacionalitat
0,1,Dona,Ciutat Vella,el Raval,1,395,1,0-4 anys,2020,Espanyola
1,1,Dona,Ciutat Vella,el Barri Gòtic,2,102,2,0-4 anys,2020,Espanyola
2,1,Dona,Ciutat Vella,la Barceloneta,3,131,3,0-4 anys,2020,Espanyola
3,1,Dona,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,185,4,0-4 anys,2020,Espanyola
4,2,Dona,Eixample,el Fort Pienc,5,419,5,0-4 anys,2020,Espanyola
...,...,...,...,...,...,...,...,...,...,...
6127,10,Home,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,0,6128,100 anys i més,2020,Estrangera
6128,10,Home,Sant Martí,el Besòs i el Maresme,70,0,6129,100 anys i més,2020,Estrangera
6129,10,Home,Sant Martí,Provençals del Poblenou,71,0,6130,100 anys i més,2020,Estrangera
6130,10,Home,Sant Martí,Sant Martí de Provençals,72,0,6131,100 anys i més,2020,Estrangera
6131,10,Home,Sant Martí,la Verneda i la Pau,73,0,6132,100 anys i més,2020,Estrangera

In [370]:
sub_df2 = sub_df2.rename(columns = {"Nom_Districte": "District", 
                                    "Codi_Districte" : "District_Code", 
                                    "Nom_Barri": "Neighborhood",
                                    "Codi_Barri": "Neighborhood_Code",
                                    "Sexe": "Sex",
                                    "Edat_quinquennal": "Five-Year_Age",
                                    "Nacionalitat": "Nationality",
                                    "Nombre":"Population"})

In [371]:
sub_df2

,District_Code,Sex,District,Neighborhood,Neighborhood_Code,Population,_id,Five-Year_Age,Any,Nationality
0,1,Dona,Ciutat Vella,el Raval,1,395,1,0-4 anys,2020,Espanyola
1,1,Dona,Ciutat Vella,el Barri Gòtic,2,102,2,0-4 anys,2020,Espanyola
2,1,Dona,Ciutat Vella,la Barceloneta,3,131,3,0-4 anys,2020,Espanyola
3,1,Dona,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,185,4,0-4 anys,2020,Espanyola
4,2,Dona,Eixample,el Fort Pienc,5,419,5,0-4 anys,2020,Espanyola
...,...,...,...,...,...,...,...,...,...,...
6127,10,Home,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,0,6128,100 anys i més,2020,Estrangera
6128,10,Home,Sant Martí,el Besòs i el Maresme,70,0,6129,100 anys i més,2020,Estrangera
6129,10,Home,Sant Martí,Provençals del Poblenou,71,0,6130,100 anys i més,2020,Estrangera
6130,10,Home,Sant Martí,Sant Martí de Provençals,72,0,6131,100 anys i més,2020,Estrangera
6131,10,Home,Sant Martí,la Verneda i la Pau,73,0,6132,100 anys i més,2020,Estrangera

In [372]:
sub_df2['Nationality'].value_counts()

Estrangera    3066
Espanyola     3066
Name: Nationality, dtype: int64

Extranjera

Española

In [373]:
nationality={"Estrangera": "Foreign",
     "Espanyola": "Spain"}

In [374]:
sub_df2["Nationality"] = sub_df2["Nationality"].map(nationality)

In [375]:
sub_df2['Five-Year_Age'].value_counts()

90-94 anys        292
70-74 anys        292
30-34 anys        292
5-9 anys          292
20-24 anys        292
85-89 anys        292
75-79 anys        292
35-39 anys        292
50-54 anys        292
95-99 anys        292
60-64 anys        292
80-84 anys        292
100 anys i més    292
15-19 anys        292
0-4 anys          292
40-44 anys        292
45-49 anys        292
55-59 anys        292
25-29 anys        292
65-69 anys        292
10-14 anys        292
Name: Five-Year_Age, dtype: int64

In [376]:
dic4 = {"90-94 anys":"90-94 years",
"70-74 anys": "70-74 years",
"30-34 anys":"30-34 years",
"5-9 anys":"5-9 years",
"20-24 anys":"20-24 years",
"85-89 anys":"85-89 years",
"75-79 anys":"75-79 years",
"35-39 anys":"35-39 years",
"50-54 anys":"50-54 years",
"95-99 anys":"95-99 years",
"60-64 anys":"60-64 years",
"80-84 anys":"80-84 years",
"100 anys i més":"100 years or older",
"15-19 anys":"15-19 years",
"0-4 anys":"0-4 years",
"40-44 anys":"40-44 years",
"45-49 anys":"45-49 years",
"55-59 anys":"55-59 years",
"25-29 anys":"25-29 years",
"65-69 anys":"65-69 years",
"10-14 anys":"10-14 years"}

In [377]:
sub_df2["Five-Year_Age"] = sub_df2["Five-Year_Age"].map(dic4)

In [378]:
sub_df2["Sex"] = sub_df2["Sex"].map(sex)

In [379]:
table2 = sub_df2.drop(columns=["_id", "Any"])

In [380]:
table2

,District_Code,Sex,District,Neighborhood,Neighborhood_Code,Population,Five-Year_Age,Nationality
0,1,Women,Ciutat Vella,el Raval,1,395,0-4 years,Spain
1,1,Women,Ciutat Vella,el Barri Gòtic,2,102,0-4 years,Spain
2,1,Women,Ciutat Vella,la Barceloneta,3,131,0-4 years,Spain
3,1,Women,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,185,0-4 years,Spain
4,2,Women,Eixample,el Fort Pienc,5,419,0-4 years,Spain
...,...,...,...,...,...,...,...,...
6127,10,Men,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,0,100 years or older,Foreign
6128,10,Men,Sant Martí,el Besòs i el Maresme,70,0,100 years or older,Foreign
6129,10,Men,Sant Martí,Provençals del Poblenou,71,0,100 years or older,Foreign
6130,10,Men,Sant Martí,Sant Martí de Provençals,72,0,100 years or older,Foreign
6131,10,Men,Sant Martí,la Verneda i la Pau,73,0,100 years or older,Foreign

In [381]:
#sub_df2.groupby(['Distrito', 'Codigo_Distrito', 'Barrio', 'Codigo_Barrio', 'Sexo', 'Edad_Quinquenal', 'Nacionalidad', 'Poblacion']).sum()

Population of the city of Barcelona according to sex and place of birth

In [382]:
url3 = 'https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=e8ea4f81-0cc2-4503-ae31-b123b559bde0&limit=3066'
fileobj3 = json.load(urlopen(url3))
#print(fileobj4)

In [383]:
fileobj3.keys()

dict_keys(['help', 'success', 'result'])

In [384]:
fileobj3['result'].keys()

dict_keys(['resource_id', 'fields', 'records', '_links', 'limit', 'total'])

In [385]:
sub_df3 = pd.json_normalize(fileobj3['result']['records'])

In [386]:
sub_df3

,Codi_Districte,Sexe,Nom_Districte,Nom_Barri,Codi_Barri,Nombre,_id,Any,Lloc_de_naixement
0,1,Dona,Ciutat Vella,el Raval,1,6076,1,2020,Barcelona ciutat
1,1,Dona,Ciutat Vella,el Barri Gòtic,2,2210,2,2020,Barcelona ciutat
2,1,Dona,Ciutat Vella,la Barceloneta,3,2928,3,2020,Barcelona ciutat
3,1,Dona,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,3370,4,2020,Barcelona ciutat
4,2,Dona,Eixample,el Fort Pienc,5,7744,5,2020,Barcelona ciutat
...,...,...,...,...,...,...,...,...,...
3061,10,Home,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,1566,3062,2020,Estranger
3062,10,Home,Sant Martí,el Besòs i el Maresme,70,5860,3063,2020,Estranger
3063,10,Home,Sant Martí,Provençals del Poblenou,71,2336,3064,2020,Estranger
3064,10,Home,Sant Martí,Sant Martí de Provençals,72,2384,3065,2020,Estranger
3065,10,Home,Sant Martí,la Verneda i la Pau,73,2677,3066,2020,Estranger

In [387]:
sub_df3['Lloc_de_naixement'].value_counts()

Castella-la Manxa             146
Canàries                      146
Cantàbria                     146
Comunitat de Madrid           146
Castella i Lleó               146
Resta Catalunya               146
Aragó                         146
Rioja, La                     146
Ceuta                         146
Estranger                     146
Melilla                       146
Principat d'Astúries          146
Comunitat Valenciana          146
Extremadura                   146
Barcelona ciutat              146
Illes Balears                 146
País Basc                     146
Regió de Múrcia               146
Galícia                       146
Andalusia                     146
Comunitat Foral de Navarra    146
Name: Lloc_de_naixement, dtype: int64

Castilla La Mancha

Canarias

Cantabria

Comunidad de Madrid

Castilla y León

Resto de Cataluña

Aragón

La Rioja

Ceuta

extranjero

Melilla

Principado de Asturias

Comunidad Valenciana

Extremadura

Barcelona ciudad

Islas Baleares

país Vasco

Región de Murcia

Galicia

Andalucía

Comunidad Foral de Navarra

In [388]:
sub_df3 = sub_df3.rename(columns = {"Nom_Districte": "District", 
                                    "Codi_Districte" : "District_Code", 
                                    "Nom_Barri": "Neighborhood",
                                    "Codi_Barri": "Neighborhood_Code",
                                    "Sexe": "Sex",
                                    "Lloc_de_naixement":"Place_of_birth",
                                    "Nombre":"Population"})

In [389]:
sub_df3

,District_Code,Sex,District,Neighborhood,Neighborhood_Code,Population,_id,Any,Place_of_birth
0,1,Dona,Ciutat Vella,el Raval,1,6076,1,2020,Barcelona ciutat
1,1,Dona,Ciutat Vella,el Barri Gòtic,2,2210,2,2020,Barcelona ciutat
2,1,Dona,Ciutat Vella,la Barceloneta,3,2928,3,2020,Barcelona ciutat
3,1,Dona,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,3370,4,2020,Barcelona ciutat
4,2,Dona,Eixample,el Fort Pienc,5,7744,5,2020,Barcelona ciutat
...,...,...,...,...,...,...,...,...,...
3061,10,Home,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,1566,3062,2020,Estranger
3062,10,Home,Sant Martí,el Besòs i el Maresme,70,5860,3063,2020,Estranger
3063,10,Home,Sant Martí,Provençals del Poblenou,71,2336,3064,2020,Estranger
3064,10,Home,Sant Martí,Sant Martí de Provençals,72,2384,3065,2020,Estranger
3065,10,Home,Sant Martí,la Verneda i la Pau,73,2677,3066,2020,Estranger

In [390]:
communities = {"Castella-la Manxa":"Castilla-La Mancha",
"Canàries":"Canary Islands",
"Cantàbria":"Cantabria",
"Comunitat de Madrid":"Community of Madrid",
"Castella i Lleó":"Castile and Leon",
"Resta Catalunya":"Rest of Catalonia",
"Aragó":"Aragon",
"Rioja, La":"The Rioja",
"Ceuta":"Ceuta",
"Estranger":"Foreign",
"Melilla":"Melilla",
"Principat d'Astúries":"Principality of Asturias",
"Comunitat Valenciana":"Valencian Community",
"Extremadura":"Extremadura",
"Barcelona ciutat":"Barcelona city",
"Illes Balears":"Balearic islands",
"País Basc":"Basque Country",
"Regió de Múrcia":"Region of Murcia",
"Galícia":"Galicia",
"Andalusia":"Andalusia",
"Comunitat Foral de Navarra":"Foral Community of Navarre"}

In [391]:
sub_df3["Place_of_birth"] = sub_df3["Place_of_birth"].map(communities)

In [392]:
sub_df3["Sex"] = sub_df3["Sex"].map(sex)

In [393]:
table3 = sub_df3.drop(columns= ["_id", "Any"])

In [394]:
table3

,District_Code,Sex,District,Neighborhood,Neighborhood_Code,Population,Place_of_birth
0,1,Women,Ciutat Vella,el Raval,1,6076,Barcelona city
1,1,Women,Ciutat Vella,el Barri Gòtic,2,2210,Barcelona city
2,1,Women,Ciutat Vella,la Barceloneta,3,2928,Barcelona city
3,1,Women,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,3370,Barcelona city
4,2,Women,Eixample,el Fort Pienc,5,7744,Barcelona city
...,...,...,...,...,...,...,...
3061,10,Men,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,1566,Foreign
3062,10,Men,Sant Martí,el Besòs i el Maresme,70,5860,Foreign
3063,10,Men,Sant Martí,Provençals del Poblenou,71,2336,Foreign
3064,10,Men,Sant Martí,Sant Martí de Provençals,72,2384,Foreign
3065,10,Men,Sant Martí,la Verneda i la Pau,73,2677,Foreign

In [395]:
sub_df3.groupby(['District', 'District_Code', 'Neighborhood', 'Neighborhood_Code', 'Sex', 'Place_of_birth', 'Population']).sum()

                                                                                                                                      _id
District            District_Code Neighborhood                          Neighborhood_Code Sex   Place_of_birth           Population
Ciutat Vella        1             Sant Pere, Santa Caterina i la Ribera 4                 Men   Andalusia                295         1683
                                                                                                Aragon                   94          1756
                                                                                                Balearic islands         23          1902
                                                                                                Barcelona city           3469        1537
                                                                                                Basque Country           68          2705
...                                                                                                                                   ...
Sarrià-Sant Gervasi 5             les Tres Torres                       24                Women Principality of Asturias 29           316
                                                                                                Region of Murcia         11          1046
                                                                                                Rest of Catalonia        801           97
                                                                                                The Rioja                9           1265
                                                                                                Valencian Community      112          754

[3066 rows x 1 columns]

Population of the city of Barcelona according to sex and nationality

In [396]:
url4 = 'https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search?resource_id=f25b814e-6c7a-4d5f-904a-398e75b2d3f1&limit=16102'
fileobj4 = json.load(urlopen(url4))
#print(fileobj5)

In [397]:
fileobj4.keys()

dict_keys(['help', 'success', 'result'])

In [398]:
fileobj4['result'].keys()

dict_keys(['resource_id', 'fields', 'records', '_links', 'limit', 'total'])

In [399]:
sub_df4 = pd.json_normalize(fileobj4['result']['records'])

In [400]:
sub_df4

,Codi_Districte,Sexe,Nom_Districte,Nom_Barri,Codi_Barri,Nombre,_id,Any,Nacionalitat
0,1,Dona,Ciutat Vella,el Raval,1,11405,1,2020,Espanya
1,1,Dona,Ciutat Vella,el Barri Gòtic,2,4141,2,2020,Espanya
2,1,Dona,Ciutat Vella,la Barceloneta,3,4730,3,2020,Espanya
3,1,Dona,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,6468,4,2020,Espanya
4,2,Dona,Eixample,el Fort Pienc,5,12900,5,2020,Espanya
...,...,...,...,...,...,...,...,...,...
16097,10,Home,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,0,16098,2020,Apàtrides / No consta
16098,10,Home,Sant Martí,el Besòs i el Maresme,70,2,16099,2020,Apàtrides / No consta
16099,10,Home,Sant Martí,Provençals del Poblenou,71,4,16100,2020,Apàtrides / No consta
16100,10,Home,Sant Martí,Sant Martí de Provençals,72,2,16101,2020,Apàtrides / No consta
16101,10,Home,Sant Martí,la Verneda i la Pau,73,0,16102,2020,Apàtrides / No consta

In [401]:
sub_df4['Nacionalitat'].value_counts()

Bèlgica                   292
Senegal                   292
Turquia                   292
Rússia                    292
Índia                     292
El Salvador               292
Geòrgia                   292
Nicaragua                 292
Colòmbia                  292
Alemanya                  292
Oceania                   292
Irlanda                   292
Marroc, el                292
Estats Units, els         292
Filipines                 292
Japó                      292
Portugal                  292
Ucraïna                   292
Polònia                   292
Hongria                   292
Romania                   292
Resta països d'Àsia       292
Argentina                 292
Paraguai                  292
Suècia                    292
Hondures                  292
Xina                      292
República Dominicana      292
Cuba                      292
Veneçuela                 292
Resta països d'Europa     292
Armènia                   292
Bangladesh                292
Suïssa                    292
Xile                      292
Uruguai                   292
Bolívia                   292
Nigèria                   292
Resta països d'Àmerica    292
Iran                      292
Països Baixos             292
Grècia                    292
Perú                      292
Equador                   292
Resta països d'Àfrica     292
Nepal                     292
Apàtrides / No consta     292
Algèria                   292
Pakistan                  292
Mèxic                     292
Brasil                    292
Bulgària                  292
Regne Unit                261
França                    219
Espanya                   219
Itàlia                    219
Name: Nacionalitat, dtype: int64

In [402]:
sub_df4 = sub_df4.rename(columns = {"Nom_Districte": "District", 
                                    "Codi_Districte" : "District_Code", 
                                    "Nom_Barri": "Neighborhood",
                                    "Codi_Barri": "Neighborhood_Code",
                                    "Sexe": "Sex",
                                    "Nacionalitat": "Nationality",
                                    "Nombre":"Population"})

In [403]:
sub_df4

,District_Code,Sex,District,Neighborhood,Neighborhood_Code,Population,_id,Any,Nationality
0,1,Dona,Ciutat Vella,el Raval,1,11405,1,2020,Espanya
1,1,Dona,Ciutat Vella,el Barri Gòtic,2,4141,2,2020,Espanya
2,1,Dona,Ciutat Vella,la Barceloneta,3,4730,3,2020,Espanya
3,1,Dona,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,6468,4,2020,Espanya
4,2,Dona,Eixample,el Fort Pienc,5,12900,5,2020,Espanya
...,...,...,...,...,...,...,...,...,...
16097,10,Home,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,0,16098,2020,Apàtrides / No consta
16098,10,Home,Sant Martí,el Besòs i el Maresme,70,2,16099,2020,Apàtrides / No consta
16099,10,Home,Sant Martí,Provençals del Poblenou,71,4,16100,2020,Apàtrides / No consta
16100,10,Home,Sant Martí,Sant Martí de Provençals,72,2,16101,2020,Apàtrides / No consta
16101,10,Home,Sant Martí,la Verneda i la Pau,73,0,16102,2020,Apàtrides / No consta

In [404]:
countries = {"Bèlgica":"Belgium",
"Senegal":"Senegal",
"Turquia":"Turkey",
"Rússia":"Russia",
"Índia":"India",
"El Salvador":"El Salvador",
"Geòrgia":"Georgia",
"Nicaragua":"Nicaragua",
"Colòmbia":"Colombia",
"Alemanya":"Germany",
"Oceania":"Oceania",
"Irlanda":"Ireland",
"Marroc, el":"Morocco",
"Estats Units, els":"United States",
"Filipines":"Philippines",
"Japó":"Japan",
"Portugal":"Portugal",
"Ucraïna":"Ukraine",
"Polònia":"Poland",
"Hongria":"Hungary",
"Romania":"Romania",
"Resta països d'Àsia":"Other Asian countries",
"Argentina":"Argentina",
"Paraguai":"Paraguay",
"Suècia":"Sweden",
"Hondures":"Honduras",
"Xina":"China",
"República Dominicana":"Dominican Republic",
"Cuba":"Cuba",
"Veneçuela":"Venezuela",
"Resta països d'Europa":"Rest of European countries",
"Armènia":"Armenia",
"Bangladesh":"Bangladesh",
"Suïssa":"Swiss",
"Xile":"Chile",
"Uruguai":"Uruguay",
"Bolívia":"Bolivia",
"Nigèria":"Nigeria",
"Resta països d'Àmerica":"Other countries in America",
"Iran":"Iran",
"Països Baixos":"Netherlands",
"Grècia":"Greece",
"Perú":"Peru",
"Equador":"Ecuador",
"Resta països d'Àfrica":"Other countries in Africa",
"Nepal":"Nepal",
"Apàtrides / No consta":"Stateless / Not listed",
"Algèria":"Algeria",
"Pakistan":"Pakistan",
"Mèxic":"Mexico",
"Brasil":"Brazil",
"Bulgària":"Bulgaria",
"Regne Unit":"United Kingdom",
"França":"France",
"Espanya":"Spain",
"Itàlia":"Italy"}

In [406]:
sub_df4["Nationality"] = sub_df4["Nationality"].map(countries)

In [407]:
sub_df4["Sex"] = sub_df4["Sex"].map(sex)

In [408]:
sub_df4

,District_Code,Sex,District,Neighborhood,Neighborhood_Code,Population,_id,Any,Nationality
0,1,Women,Ciutat Vella,el Raval,1,11405,1,2020,Spain
1,1,Women,Ciutat Vella,el Barri Gòtic,2,4141,2,2020,Spain
2,1,Women,Ciutat Vella,la Barceloneta,3,4730,3,2020,Spain
3,1,Women,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,6468,4,2020,Spain
4,2,Women,Eixample,el Fort Pienc,5,12900,5,2020,Spain
...,...,...,...,...,...,...,...,...,...
16097,10,Men,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,0,16098,2020,Stateless / Not listed
16098,10,Men,Sant Martí,el Besòs i el Maresme,70,2,16099,2020,Stateless / Not listed
16099,10,Men,Sant Martí,Provençals del Poblenou,71,4,16100,2020,Stateless / Not listed
16100,10,Men,Sant Martí,Sant Martí de Provençals,72,2,16101,2020,Stateless / Not listed
16101,10,Men,Sant Martí,la Verneda i la Pau,73,0,16102,2020,Stateless / Not listed

In [409]:
table4 = sub_df4.drop(columns= ["_id", "Any"])

In [410]:
table4

,District_Code,Sex,District,Neighborhood,Neighborhood_Code,Population,Nationality
0,1,Women,Ciutat Vella,el Raval,1,11405,Spain
1,1,Women,Ciutat Vella,el Barri Gòtic,2,4141,Spain
2,1,Women,Ciutat Vella,la Barceloneta,3,4730,Spain
3,1,Women,Ciutat Vella,"Sant Pere, Santa Caterina i la Ribera",4,6468,Spain
4,2,Women,Eixample,el Fort Pienc,5,12900,Spain
...,...,...,...,...,...,...,...
16097,10,Men,Sant Martí,Diagonal Mar i el Front Marítim del Poblenou,69,0,Stateless / Not listed
16098,10,Men,Sant Martí,el Besòs i el Maresme,70,2,Stateless / Not listed
16099,10,Men,Sant Martí,Provençals del Poblenou,71,4,Stateless / Not listed
16100,10,Men,Sant Martí,Sant Martí de Provençals,72,2,Stateless / Not listed
16101,10,Men,Sant Martí,la Verneda i la Pau,73,0,Stateless / Not listed

In [411]:
sub_df4.groupby(['District', 'District_Code', 'Neighborhood', 'Neighborhood_Code', 'Sex', 'Nationality', 'Population']).sum()

                                                                                                                             _id
District            District_Code Neighborhood                          Neighborhood_Code Sex   Nationality    Population
Ciutat Vella        1             Sant Pere, Santa Caterina i la Ribera 4                 Men   Algeria        78          19030
                                                                                                Argentina      193         20198
                                                                                                Armenia        4           23118
                                                                                                Bangladesh     46          22826
                                                                                                Belgium        63          18008
...                                                                                                                          ...
Sarrià-Sant Gervasi 5             les Tres Torres                       24                Women Ukraine        12           9142
                                                                                                United Kingdom 22            243
                                                                                                United States  73          12792
                                                                                                Uruguay        4           13668
                                                                                                Venezuela      22          11770

[8176 rows x 1 columns]

In [414]:
table1.to_csv("sex and academic level.csv")

In [415]:
table2.to_csv("sex, five-year age and nationality.csv")

In [416]:
table3.to_csv("sex and place of birth.csv")

In [412]:
table4.to_csv("sex and nationality.csv")